num1=int(input("enter the first number"))
num2=int(input("enter the second number"))
sum=num1+num2
subtraction=num1-num2
multiplication =num1*num2
division=num1/num2
print("Sum=", sum)
print("Subtraction=", subtraction)
print("Multiplication=", multiplication)
print("Division=", division)